export default {
  intro: 'Intro',
  project: 'Project',
  pages: 'Pages',
  about: 'About',
  slogan: 'E4 BD A0 E5 A5 BD E9 99 B4 E7 94 9F E4 BA BA',
  welcome1: 'Hello, I\'m Landers',
  welcome2: 'A developer and Security engineer.',
  cv: 'CV',
  cv1: 'is attached.',
  timeline: 'Site Log',
  work: 'Work Experience',
  intro1: 'Hello, I\'m Landers from HUST(HuaZhong University of sci&tech.)',
  intro2: 'Passionate about programming, food, biking, movies, games and CS:GO!',
  intro3: 'This is a place where I record my study, relaxation, and enjoyment. Welcome!',
  intro_footer: 'Graduated from School of Electronic Information and Communications, HUST.',
  update2023: 'Update 2023',
  update2024: 'Update 2024',
  update2025: 'Update 2025',
  update1: 'Work in Huawei Technologies Co., Ltd. as a developer.',
  update2: 'Work in Huawei Technologies Co., Ltd. as a security engineer.',
  update3: 'Thank you Huawei, for allowing me to see the World! Goodbye.',
  find: 'Where you can find me.',
  about1: 'Just a programmer ...',
  steam: 'My Steam',
  email: 'My Email',
  telegram: 'My Telegram',
  facebook: 'My Facebook',
  thanks: 'Special thanks to Michael Zhang for the translation work',

  site1: 'Wordpress - first site 2017-09-01',
  site2: 'Register domain lrenj.top 2018',
  site3: 'Write site with Flask 2019',
  site4: 'Register domain renj.io 2020',
  site5: 'Switch technology stack to go&react 2020',
  site6: 'What you see now 2022',

  work1: 'HuaZhong University of sci&tech 2016-2020',
  work2: 'CETC 41 (intern) 2019',
  work3: 'Huawei (NCE-Go) 2020-2021',
  work4: 'Huawei (NCE-Js/Ts) 2022',
  work5: 'Huawei (ICSL-Security) 2023',
  work6: 'Huawei (Calculation) 2024',
  title: {
    start: 'Start',
    introduction: 'Introduction',
    work: 'Work Experience',
    projects: 'Projects',
    social: 'Social',
    timeline: 'Timeline'
  },
  projects: {
    line1: 'Interpret freedom through code and record happiness through programming.',
    line2: 'A omnivore of programming languages: tasting Golang, Python, Javascript, Rust and more.',
    line3: 'Our goals',
    line4: 'Write what I think, do what I love, and make life more wonderful and interesting!',
    hide1: 'What\'s our goals?',
    hide2: 'Is our goal the stars and the sea? Or...?',
  }
}