export default {
  intro: 'Intro',
  project: 'Project',
  pages: 'Pages',
  about: 'About',
  slogan: 'Don\'t try so hard, the best things come when you least expect them to.',
  welcome1: 'Hello, I\'m Landers',
  welcome2: 'A developer and Security engineer.',
  cv: 'CV',
  cv1: 'is attached.',
  timeline: 'Timeline',
  work: 'Work Experience',
  intro1: 'Hello, I\'m Landers from HUST(HuaZhong University of sci&tech.)',
  intro2: 'This is a place where I record my study, relaxation, and enjoyment. Welcome!',
  intro3: 'Graduated from School of Electronic Information and Communications, HUST.',
  update2023: 'Update 2023',
  update2024: 'Update 2024',
  update1: 'Work in Huawei Technologies Co., Ltd. as a developer.',
  update2: 'Work in Huawei Technologies Co., Ltd. as a security engineer.',
  find: 'Where you can find me.',
  about1: 'Just a programmer ...',
  steam: 'My Steam',
  email: 'My Email',
  telegram: 'My Telegram',
  facebook: 'My Facebook',
}