export default {
  intro: 'Intro',
  project: 'Project',
  pages: 'Pages',
  about: 'About',
  slogan: 'Don\'t try so hard, the best things come when you least expect them to.',
  welcome1: 'Hello, I\'m Landers',
  welcome2: 'A developer and Security engineer.',
  cv: 'CV',
  cv1: 'is attached.',
  timeline: 'Site Log',
  work: 'Work Experience',
  intro1: 'Hello, I\'m Landers from HUST(HuaZhong University of sci&tech.)',
  intro2: 'Passionate about programming, food, biking, movies, games and CS:GO!',
  intro3: 'This is a place where I record my study, relaxation, and enjoyment. Welcome!',
  intro_footer: 'Graduated from School of Electronic Information and Communications, HUST.',
  update2023: 'Update 2023',
  update2024: 'Update 2024',
  update1: 'Work in Huawei Technologies Co., Ltd. as a developer.',
  update2: 'Work in Huawei Technologies Co., Ltd. as a security engineer.',
  update3: 'Work in Huawei Technologies Co., Ltd. as the Owner of Requirements-Management Tool.',
  find: 'Where you can find me.',
  about1: 'Just a programmer ...',
  steam: 'My Steam',
  email: 'My Email',
  telegram: 'My Telegram',
  facebook: 'My Facebook',
  thanks: 'Special thanks to Michael Zhang for the translation work',

  site1: 'wordpress - first site 2017-09-01',
  site2: 'register domain lrenj.top 2018',
  site3: 'write site with Flask 2019',
  site4: 'register domain renj.io 2020',
  site5: 'switch tech. to go&react 2020',
  site6: 'what you see now 2022',

  work1: 'HuaZhong University of sci&tech 2016-2020',
  work2: 'CETC 41 (intern) 2019',
  work3: 'Huawei (NCE-Go) 2020-2021',
  work4: 'Huawei (NCE-Js/Ts) 2022',
  work5: 'Huawei (ICSL-Security) 2023',
  work6: 'Huawei (Calculation) 2024',
}