export default {
  intro: '简介',
  project: '项目',
  pages: '页面',
  about: '关于',
  slogan: '不要着急，最好的总会在最不经意的时候出现',
  welcome1: '你好，我是Landers',
  welcome2: '一个软件工程师 & 安全测试工程师。',
  cv: '简历',
  cv1: '请见',
  timeline: '时间线',
  work: '工作经历',
  intro1: '你好，我是Landers，毕业于华中科技大学',
  intro2: '这是我学习，放松，分享生活的地方',
  intro3: '来自华中科技大学 - 电子信息与通信学院',
  update2023: '2023更新',
  update2024: '2024更新',
  update1: '华为 - 软件开发工程师',
  update2: '华为 - 安全测试工程师',
  find: '在哪里可以找到我',
  about1: '一个普普通通的开发者',
  steam: '我的Steam',
  email: '我的邮箱',
  telegram: '我的Telegram频道',
  facebook: '我的Facebook主页'
}