export default {
  intro: '简介',
  project: '项目',
  pages: '页面',
  about: '关于',
  slogan: '不要着急，最好的总会在最不经意的时候出现',
  welcome1: '你好，我是Landers',
  welcome2: '一个软件工程师 & 安全测试工程师。',
  cv: '简历',
  cv1: '请见',
  timeline: '时间线',
  work: '工作经历',
  intro1: '你好，我是Landers，毕业于华中科技大学',
  intro2: '这是我学习，放松，分享生活的地方',
  intro3: '来自华中科技大学 - 电子信息与通信学院',
  update2023: '2023更新',
  update2024: '2024更新',
  update1: '华为(公共开发部) - 软件开发工程师',
  update2: '华为(ICSL) - 安全测试工程师',
  update3: '华为(计算产品线) - 软件开发工程师',
  find: '在哪里可以找到我',
  about1: '一个普普通通的开发者',
  steam: '我的Steam',
  email: '我的邮箱',
  telegram: '我的Telegram频道',
  facebook: '我的Facebook主页',
  thanks: '特别感谢Michael Zhang • 张先生提供的翻译工作',

  site1: 'wordpress - 我的第一个站点 2017-09-01',
  site2: '注册域名lrenj.top 2018',
  site3: '使用Flask编写网站 2019',
  site4: '注册域名renj.io 2020',
  site5: '将网站技术栈切换为go和react 2020',
  site6: '你现在看到的样子 2022',

  work1: '华中科技大学 2016-2020',
  work2: '中电41所 (实习) 2019',
  work3: '华为 (NCE-Go后端开发) 2020-2021',
  work4: '华为 (NCE-前端开发) 2022',
  work5: '华为 (ICSL-安全测试) 2023',
  work6: '华为 (计算产品线) 2024',
}